# Generated by Django 5.2.10 on 2026-02-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_options_remove_task_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
